server:
  compression:
    min-response-size: 2KB
    enabled: true
    mime-types: image/jpeg, image/gif, image/png, video/mp4, video/mpeg, video/mpeg4-generic, application/octet-stream
    ffmpeg: ${FFMPEG_PATH:ffmpeg}
    ffprobe: ${FFPROBE_PATH:ffprobe}